database:
  image: mysql:latest
  restart: always
  expose: 
  - "3306"
  environment:
  - MYSQL_ROOT_PASSWORD=triber-sensor-root
  - MYSQL_DATABASE=triber-sensor
  - MYSQL_USER=triber-sensor
  - MYSQL_PASSWORD=triber-sensor
  container_name: triber-sensor-db
  ports:
  - "3306:3306"
elasticsearch:
  image: elasticsearch:1.7.3
  restart: always
  expose:
  - "9200"
  - "9300"
  container_name: triber-sensor-elastic
  ports:
  - "9200:9200"
  - "9300:9300"
application:
  image: triberraar/triber-sensor:latest
  restart: always
  ports:
  - "8080:8080"
  environment:
  - SPRING_DATASOURCE_URL=jdbc:mysql://triber-sensor-db:3306/triber-sensor 
  - SPRING_DATASOURCE_USERNAME=triber-sensor
  - SPRING_DATASOURCE_PASSWORD=triber-sensor
  - SPRING_DATA_ELASTICSEARCH_CLUSTER-NODES=triber-sensor-elastic:9300
  - SPRING_DATA_ELASTICSEARCH_PROPERTIES_NODE_LOCAL=false
  - SPRING_DATA_ELASTICSEARCH_PROPERTIES_NODE_DATA=false
  - SPRING_DATA_ELASTICSEARCH_NODE_CLIENT=true
  - SPRING_PROFILES_ACTIVE=dev
  links:
  - database
  - elasticsearch
  container_name: triber-sensor